In [1]:
import pandas as pd

# Load dataset
ts_chart = pd.read_pickle('../../bld/out/data_processed/BTC_POT_chart_data.p')
ts_trade = pd.read_pickle('../../bld/out/data_processed/BTC_POT_trade_history.p')

# Change column names
ts_chart.columns = map(str.upper, ts_chart.columns)
ts_chart['CHART'] = True

ts_trade.columns = map(str.upper, ts_trade.columns)
ts_trade['TRADE'] = True

# Merge datasets
ts = ts_chart.join(ts_trade, how='outer')

# Fill NaNs
ts.CHART.fillna(False, inplace=True)
ts.TRADE.fillna(False, inplace=True)

In [7]:
ts.head()

,CLOSE,HIGH_LAG_1,LOW_LAG_1,OPEN_LAG_1,QUOTEVOLUME_LAG_1,VOLUME_LAG_1,WEIGHTEDAVERAGE_LAG_1,CHART,AMOUNT,RATE,TOTAL,TYPE,TRADE
date,,,,,,,,,,,,,
2014-07-14 23:01:56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,200.0,0.000017,0.003366,buy,True
2014-07-14 23:03:09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,200.0,0.000017,0.003368,buy,True
2014-07-14 23:03:21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,100.0,0.000017,0.001685,buy,True
2014-07-14 23:08:20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,200.0,0.000017,0.003372,buy,True
2014-07-14 23:08:20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,200.0,0.000017,0.003374,buy,True